---
- name: Delete Che
  command: "oc delete all -l app=che -n {{ namespace }}"

- name: Delete Che configmap
  command: "oc delete cm che -n {{ namespace }}"
  ignore_errors: yes

- name: Delete Che ServiceAccount RoleBinding
  command: "oc delete rolebinding che-admin -n {{ namespace }}"
  ignore_errors: yes

- name: Delete Che ServiceAccount
  command: "oc delete serviceaccount che -n {{ namespace }}"
  ignore_errors: yes
